Hi Team –

 

Created tables in Data Lab (NON_CRTFD_MCKINSEY_COC), with below filters

 

ASO records  (FUNDG_CLS_CD ='FCM002')
LOB_SHRT_DESC:  Commercial  (no Commercial Individual/ Commercial Local segregation)
MPR_IND=’N’
Only 5 Master Client Groups
SNAP : 202607 for Uncompleted and 202606 for Completed
 

Schema:  DL_MCKINSEY_COC_STG

COC_ACTL_HCC_RPT_SMRY_ASO_STG
WORK_ELEVATE_COC_CLAIM_DETAIL_ASO_STG
WORK_ELEVATE_COC_MBR_DETAIL_ASO_STG
COC_CMN_TRND_MTRC_INSGHT_ASO_STG ( Statistical Model O/p in STG) , with additional column MSTR_CLNT_GRP_NM –  OON Loaded. IP Med/Surg- DRG in progress, remaining slices loaded.
COC_CMN_DATA_INSGHT_ASO_STG ( Deep Research and Deep Dive O/p in STG) , with additional column MSTR_CLNT_GRP_NM– Yet to load
WORK_COC_ELEVATE_AUTO_DETECT_KPI_ASO (UI Worktable)-, with additional column MSTR_CLNT_GRP_NM– Completed(LOB level data loaded)  
 

 

Schema: DL_MCKINSEY_COC:

MSTR_CLNT_GRP_SUB_GRP_ASO (Master Client Groups)
COC_ACTL_HCC_RPT_SMRY_ASO ( Completed Claims n Membership Data)
WORK_ELEVATE_COC_CLAIM_DETAIL_ASO (Uncompleted CLAIMS Data)
WORK_ELEVATE_COC_MBR_DETAIL_ASO ( Uncompleted MBRSHP Data)
COC_CMN_TRND_MTRC_INSGHT_ASO_STG ( Statistical Model O/p in TGT) , with additional column MSTR_CLNT_GRP_NM– OON Loaded. IP MedSurg- DRG in progress, remaining slices loaded
COC_CMN_DATA_INSGHT_ASO_STG ( Deep Research and Deep Dive O/p in TGT) , with additional column MSTR_CLNT_GRP_NM– Yet to load
 

Replica of source tables

EXECTV_DSHBRD_CNDTN_PRVLNC è  NON_CRTFD_MCKINSEY_COC.DL_MCKINSEY_COC.EXECTV_DSHBRD_CNDTN_PRVLNC_ASO
EXECTV_DSHBRD_INPAT_DRG ( required for DRG Slice) è NON_CRTFD_MCKINSEY_COC.DL_MCKINSEY_COC.EXECTV_DSHBRD_IP_DRG_ASO
 

 

 

Thanks,

Raja
