#!/usr/bin/env python3
"""
Reduction test harness for the Carelon policy comparison API.

Prior sweep (POLICY_API_STRATEGIES.md) established `code,broad_category` as the
winning KEYWORD strategy. But the raw counts it returns are unmanageable —
J3490,injection returns 722 Reimbursement policies of which 181 are Elevance,
and inspection shows a large fraction are false positives (unrelated policies
that happen to mention "ambulance" or "injection" in prose).

This harness sweeps ~96 scenarios (8 codes x 12 reduction strategies) that stack
server-side filters (POST body: lob, state, payor) with client-side filters
(title-regex, dedup by title, per-payor cap, score-threshold) on top of the
winning keyword. Goal: shrink the set to only the Elevance Reimbursement
policies that are TOPICALLY relevant to the code — target ~5-15 per code — while
retaining recall on the canonical Elevance titles seen in the ground-truth
sample dumps.

Usage:
    export SSL_CERT_FILE=/Users/AH45807/project/idiscovery-deep-research/cacert.pem
    python scripts/test_policy_api_reduction.py

Outputs:
    scripts/policy_api_reduction_results.csv    per-scenario counts + latency
    scripts/policy_api_reduction_details.json   per-scenario title breakdown
    scripts/policy_api_reduction_run.log        stdout capture

Reads `scripts/elevance_title_taxonomy.json` when present (generated by the
title-mining subagent) to drive the per-code title regex. Falls back to a
hardcoded taxonomy so this script is runnable standalone.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import sys
import time
from collections import Counter
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Any, Dict, List, Optional, Tuple

import requests

API_URL = "https://policy-comparison-api.carelon.com/policy_comparison/search"
TAXONOMY_PATH = "scripts/elevance_title_taxonomy.json"

# Winning keyword strategy per code from the prior sweep (code_and_broad).
CODES: List[Dict[str, str]] = [
    {"code": "a0427", "narrow": "ambulance",              "broad": "transportation"},
    {"code": "99291", "narrow": "critical care",          "broad": "evaluation and management"},
    {"code": "90837", "narrow": "psychotherapy",          "broad": "behavioral health"},
    {"code": "22551", "narrow": "spine fusion",           "broad": "spine surgery"},
    {"code": "71260", "narrow": "chest CT",               "broad": "diagnostic imaging"},
    {"code": "G0463", "narrow": "outpatient clinic visit","broad": "hospital outpatient"},
    {"code": "J3490", "narrow": "unclassified drug",      "broad": "injection"},
    {"code": "43239", "narrow": "upper endoscopy",        "broad": "endoscopy"},
]

# Fallback taxonomy. Prefer scripts/elevance_title_taxonomy.json when present.
# Each regex matches Elevance Reimbursement titles TOPICALLY relevant to the
# code — extracted from the 1462-entry distinct-policy-titles CSV plus the
# ambulance sample. Case-insensitive.
FALLBACK_TITLE_REGEX: Dict[str, str] = {
    "a0427": r"(?i)(transportation|ambulance)",
    "99291": r"(?i)(evaluation\s+and\s+management|\bE&M\b|critical\s+care|emergency\s+department)",
    "90837": r"(?i)(psychotherapy|behavioral\s+health|mental\s+health|counseling|substance\s+use)",
    "22551": r"(?i)(spine|spinal|fusion|orthoped|surgery|surgic|assistant.*surgeon|co.?surgeon)",
    "71260": r"(?i)(radiolog|imaging|\bCT\b|\bMR|contrast|ultrasound|diagnostic)",
    "g0463": r"(?i)(outpatient|clinic|facility|E&M|evaluation\s+and\s+management|hospital\s+outpatient)",
    "j3490": r"(?i)(drug|biological|injection|infusion|unlisted|not\s+otherwise\s+classified|\bNOC\b|J\-?code)",
    "43239": r"(?i)(endoscop|GI|gastro|colonoscop|biopsy)",
}


def load_taxonomy() -> Dict[str, str]:
    """Load title-regex per code from scripts/elevance_title_taxonomy.json when
    present; else fall back to the hardcoded FALLBACK_TITLE_REGEX above."""
    if os.path.exists(TAXONOMY_PATH):
        with open(TAXONOMY_PATH) as fp:
            tax = json.load(fp)
        out: Dict[str, str] = {}
        for code_lc, cfg in (tax.get("codes") or {}).items():
            rx = cfg.get("recommended_title_regex") or ""
            if rx:
                out[code_lc.lower()] = rx
        # merge with fallback for any missing codes
        for k, v in FALLBACK_TITLE_REGEX.items():
            out.setdefault(k, v)
        return out
    return dict(FALLBACK_TITLE_REGEX)


TITLE_REGEX = load_taxonomy()


# ----------------------------------------------------------------------------
# Strategy definitions
# ----------------------------------------------------------------------------

STRATEGIES: List[Dict[str, Any]] = [
    # Prior-sweep baseline; no extra reduction.
    {"name": "baseline",                     "kw": "code_and_broad",  "post": {}},
    # Client-side title regex only.
    {"name": "title_regex",                  "kw": "code_and_broad",  "post": {"title_regex": True}},
    # Dedup by (payor, policy_title) — collapse state fanout.
    {"name": "dedup_title",                  "kw": "code_and_broad",  "post": {"dedup_title": True}},
    # Both client filters combined — leading candidate.
    {"name": "title_regex+dedup",            "kw": "code_and_broad",  "post": {"title_regex": True, "dedup_title": True}},
    # Server-side LOB filters (mutually exclusive; each isolates one product line).
    {"name": "lob_commercial",               "kw": "code_and_broad",  "server": {"lob": ["Commercial"]},          "post": {"title_regex": True, "dedup_title": True}},
    {"name": "lob_medicaid",                 "kw": "code_and_broad",  "server": {"lob": ["Medicaid"]},            "post": {"title_regex": True, "dedup_title": True}},
    {"name": "lob_medicare_adv",             "kw": "code_and_broad",  "server": {"lob": ["Medicare Advantage"]},  "post": {"title_regex": True, "dedup_title": True}},
    # Server-side payor filter (single-call captures ~96% of Elevance — the
    # `internal` variant is only reachable via a second call; multi-value
    # payor lists return 0 rows, so we cannot union in one request).
    {"name": "payor_elevance_only",          "kw": "code_and_broad",  "server": {"payor": ["Elevance Health (external)"]},                                 "post": {}},
    {"name": "payor_elevance+title+dedup",   "kw": "code_and_broad",  "server": {"payor": ["Elevance Health (external)"]},                                 "post": {"title_regex": True, "dedup_title": True}},
    # State filter (uses NY as a sample high-volume state).
    {"name": "state_ny+title+dedup",         "kw": "code_and_broad",  "server": {"state": ["NY"]},                "post": {"title_regex": True, "dedup_title": True}},
    # Different keyword baseline stacked with client filters.
    {"name": "narrow_kw+title+dedup",        "kw": "narrow_only",     "post": {"title_regex": True, "dedup_title": True}},
    # Broad-keyword-only stacked with client filters.
    {"name": "broad_kw+title+dedup",         "kw": "broad_only",      "post": {"title_regex": True, "dedup_title": True}},
    # Top-N by API policy_score.
    {"name": "title+dedup+top10_score",      "kw": "code_and_broad",  "post": {"title_regex": True, "dedup_title": True, "top_n_by_score": 10}},
]


def build_keyword(code_entry: Dict[str, str], kw_kind: str) -> str:
    code = code_entry["code"]
    narrow = code_entry["narrow"]
    broad = code_entry["broad"]
    if kw_kind == "code_only":
        return code
    if kw_kind == "narrow_only":
        return narrow
    if kw_kind == "broad_only":
        return broad
    if kw_kind == "code_and_broad":
        return f"{code},{broad}"
    if kw_kind == "code_and_narrow":
        return f"{code},{narrow}"
    raise ValueError(f"unknown kw kind: {kw_kind}")


# ----------------------------------------------------------------------------
# API call
# ----------------------------------------------------------------------------

def call_api(
    keyword: str,
    server_filters: Optional[Dict[str, Any]] = None,
    ssl_cert: Optional[str] = None,
    timeout: int = 60,
) -> Dict[str, Any]:
    url = f"{API_URL}?keyword={keyword}&user_type=onshore"
    post_body: Dict[str, Any] = {"policy_type": ["Reimbursement"]}
    if server_filters:
        post_body.update(server_filters)
    verify = ssl_cert if ssl_cert else True
    t0 = time.time()
    try:
        resp = requests.post(
            url,
            headers={"Content-Type": "application/json"},
            json=post_body,
            verify=verify,
            timeout=timeout,
        )
        latency = time.time() - t0
        if resp.status_code >= 400:
            return {"ok": False, "status": resp.status_code, "latency_s": latency,
                    "sentencelist": [], "error": f"HTTP {resp.status_code}: {resp.text[:200]}"}
        payload = resp.json()
        return {"ok": True, "status": resp.status_code, "latency_s": latency,
                "sentencelist": payload.get("sentencelist") or [], "error": None}
    except Exception as exc:
        return {"ok": False, "status": 0, "latency_s": time.time() - t0,
                "sentencelist": [], "error": f"{type(exc).__name__}: {exc}"}


# ----------------------------------------------------------------------------
# Post-filters
# ----------------------------------------------------------------------------

def apply_post_filters(
    sentencelist: List[Dict[str, Any]],
    code: str,
    post: Dict[str, Any],
) -> Tuple[List[Dict[str, Any]], Dict[str, int]]:
    """Return (filtered_rows, stage_counts). Rows keep server structure.

    Applies (in order):
      1. Restrict to policy_type == 'Reimbursement'
      2. Optional title_regex match on `policy_title`
      3. Optional dedup by (payor, policy_title) — keep highest-score row per group
      4. Optional top-N by policy_score
    """
    stages: Dict[str, int] = {}
    rows = [s for s in sentencelist if s.get("policy_type") == "Reimbursement"]
    stages["after_reimb_only"] = len({r.get("policy_id") for r in rows})

    if post.get("title_regex"):
        rx = re.compile(TITLE_REGEX.get(code.lower(), r".*"))
        rows = [r for r in rows if rx.search(r.get("policy_title") or "")]
        stages["after_title_regex"] = len({r.get("policy_id") for r in rows})

    if post.get("dedup_title"):
        seen: Dict[Tuple[str, str], Dict[str, Any]] = {}
        for r in rows:
            key = ((r.get("payor") or ""), (r.get("policy_title") or ""))
            cur = seen.get(key)
            if cur is None:
                seen[key] = r
                continue
            # Keep the row with the higher policy_score if available.
            try:
                if float(r.get("policy_score") or 0) > float(cur.get("policy_score") or 0):
                    seen[key] = r
            except (TypeError, ValueError):
                pass
        rows = list(seen.values())
        stages["after_dedup_title"] = len({r.get("policy_id") for r in rows})

    top_n = post.get("top_n_by_score")
    if top_n:
        def _score(r: Dict[str, Any]) -> float:
            try:
                return float(r.get("policy_score") or 0)
            except (TypeError, ValueError):
                return 0.0
        rows = sorted(rows, key=_score, reverse=True)[: int(top_n)]
        stages[f"after_top_{top_n}_by_score"] = len({r.get("policy_id") for r in rows})

    return rows, stages


def summarize(rows: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Compute the metrics we compare across strategies."""
    unique_policies = {r.get("policy_id") for r in rows}
    payor_counter: Counter = Counter()
    elv_ids: set = set()
    elv_titles: set = set()
    all_titles: set = set()
    scores: List[float] = []
    for r in rows:
        payor = r.get("payor") or ""
        pid = r.get("policy_id") or ""
        title = r.get("policy_title") or ""
        payor_counter[payor] += 1
        all_titles.add(title)
        if "Elevance" in payor:
            elv_ids.add(pid)
            elv_titles.add(title)
        try:
            scores.append(float(r.get("policy_score") or 0))
        except (TypeError, ValueError):
            pass
    return {
        "reimb_unique_policies": len(unique_policies),
        "reimb_unique_titles": len(all_titles),
        "elv_unique_policies": len(elv_ids),
        "elv_unique_titles": len(elv_titles),
        "unique_payors": len(payor_counter),
        "top_payors": payor_counter.most_common(5),
        "elv_titles_sample": sorted(elv_titles)[:10],
        "median_score": (sorted(scores)[len(scores) // 2] if scores else None),
    }


# ----------------------------------------------------------------------------
# Scenario runner
# ----------------------------------------------------------------------------

def run_scenario(
    code_entry: Dict[str, str],
    strategy: Dict[str, Any],
    ssl_cert: Optional[str],
) -> Dict[str, Any]:
    code = code_entry["code"]
    keyword = build_keyword(code_entry, strategy["kw"])
    server_filters = strategy.get("server") or {}
    call = call_api(keyword, server_filters=server_filters, ssl_cert=ssl_cert)
    rows, stages = apply_post_filters(call["sentencelist"], code, strategy.get("post") or {})
    stats = summarize(rows)
    return {
        "code": code,
        "strategy": strategy["name"],
        "keyword": keyword,
        "server_filters": server_filters,
        "post_filters": strategy.get("post") or {},
        "ok": call["ok"],
        "status": call["status"],
        "latency_s": round(call["latency_s"], 2),
        "error": call["error"] or "",
        "stage_counts": stages,
        **stats,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ssl-cert", default=os.environ.get("SSL_CERT_FILE", ""))
    parser.add_argument("--concurrency", type=int, default=4)
    parser.add_argument("--out-csv",  default="scripts/policy_api_reduction_results.csv")
    parser.add_argument("--out-json", default="scripts/policy_api_reduction_details.json")
    parser.add_argument("--limit", type=int, default=0, help="First N scenarios only")
    args = parser.parse_args()

    ssl_cert = args.ssl_cert or None
    if ssl_cert and not os.path.exists(ssl_cert):
        print(f"[warn] SSL cert not found: {ssl_cert} — using system CAs", file=sys.stderr)
        ssl_cert = None

    scenarios: List[Tuple[Dict[str, str], Dict[str, Any]]] = [
        (c, s) for c in CODES for s in STRATEGIES
    ]
    if args.limit:
        scenarios = scenarios[: args.limit]

    print(f"Running {len(scenarios)} scenarios (concurrency={args.concurrency}, "
          f"taxonomy_loaded={os.path.exists(TAXONOMY_PATH)})")

    rows: List[Dict[str, Any]] = []
    with ThreadPoolExecutor(max_workers=args.concurrency) as pool:
        futs = {pool.submit(run_scenario, c, s, ssl_cert): (c, s) for c, s in scenarios}
        for i, fut in enumerate(as_completed(futs), 1):
            c, s = futs[fut]
            row = fut.result()
            rows.append(row)
            print(
                f"[{i}/{len(scenarios)}] code={row['code']:6s} "
                f"strat={row['strategy']:26s} kw={row['keyword']!r:40s} "
                f"→ reimb_pol={row['reimb_unique_policies']:4d} "
                f"reimb_titles={row['reimb_unique_titles']:3d} "
                f"elv_pol={row['elv_unique_policies']:3d} "
                f"elv_titles={row['elv_unique_titles']:2d} "
                f"({row['latency_s']}s)"
                + (f" ERR={row['error']}" if not row["ok"] else "")
            )

    rows.sort(key=lambda r: (r["code"], r["strategy"]))

    csv_cols = [
        "code", "strategy", "keyword",
        "reimb_unique_policies", "reimb_unique_titles",
        "elv_unique_policies", "elv_unique_titles",
        "unique_payors", "median_score",
        "ok", "status", "latency_s", "error",
    ]
    os.makedirs(os.path.dirname(args.out_csv), exist_ok=True)
    with open(args.out_csv, "w", newline="") as fp:
        w = csv.DictWriter(fp, fieldnames=csv_cols, extrasaction="ignore")
        w.writeheader()
        for r in rows:
            w.writerow(r)
    print(f"\nCSV written to {args.out_csv}")

    with open(args.out_json, "w") as fp:
        json.dump(rows, fp, indent=2, default=str)
    print(f"JSON written to {args.out_json}")

    # Print per-code table sorted by reimb_unique_policies ascending (smallest wins).
    print("\n" + "=" * 110)
    print(f"{'code':6s} {'strategy':28s} {'reimb_pol':>9s} {'reimb_tit':>9s} {'elv_pol':>7s} {'elv_tit':>7s} {'payors':>6s}")
    print("-" * 110)
    for r in rows:
        print(
            f"{r['code']:6s} {r['strategy']:28s} "
            f"{r['reimb_unique_policies']:9d} {r['reimb_unique_titles']:9d} "
            f"{r['elv_unique_policies']:7d} {r['elv_unique_titles']:7d} "
            f"{r['unique_payors']:6d}"
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
